"""fix food repr food name to food_name

Revision ID: 39840d3c689b
Revises: fdd6190edd74
Create Date: 2023-08-25 00:13:00.637597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39840d3c689b'
down_revision: Union[str, None] = 'fdd6190edd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
